apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.administration.pvc.image.metadata.name }}-pvc
spec:
  accessModes:
    - {{ .Values.administration.pvc.image.spec.accessModes }}
  resources:
    requests:
      storage: {{ .Values.administration.pvc.image.spec.resources.requests.storage }}