apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.administration.statefulset.metadata.name }}-statefulset
spec:
  replicas: {{ .Values.administration.statefulset.spec.replicas }}
  template:
    metadata:
      name: {{ .Values.administration.statefulset.spec.template.metadata.name }}
      labels:
        app: {{ .Values.administration.statefulset.spec.template.metadata.labels.app }}
    spec:
      containers:
        - name: {{ .Values.administration.statefulset.spec.template.spec.container.name }}-container
          image: {{ .Values.administration.statefulset.spec.template.spec.container.image }}
          ports:
            - containerPort: {{ .Values.administration.statefulset.spec.template.spec.container.port.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.administration.cm.metadata.name }}-configmap
          volumeMounts:
            - name: images
              mountPath: /var/www/html/uploads
            - name: session
              mountPath: /var/www/html/sessions
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.administration.statefulset.spec.template.spec.container.port.containerPort }}
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /inserir_noticias.php
              port: {{ .Values.administration.statefulset.spec.template.spec.container.port.containerPort }}
            initialDelaySeconds: 3
            periodSeconds: 10
            failureThreshold: 5
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: {{ .Values.administration.pvc.image.metadata.name }}-pvc
        - name: session
          persistentVolumeClaim:
            claimName: {{ .Values.administration.pvc.session.metadata.name }}-pvc
  selector:
    matchLabels:
      app: {{ .Values.administration.statefulset.spec.selector.matchLabels.app }}
  serviceName: {{ .Values.administration.statefulset.spec.serviceName }}