apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Values.database.service.metadata.name }}
spec:
  type: {{ .Values.database.statefulset.spec.type }}
  selector:
    app: {{ .Values.database.service.spec.selector.app }}
  ports:
    - port: {{ .Values.database.service.spec.ports.port }}
      #targetPort: {{ .Values.database.service.spec.ports.port }}